[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

# [project]
# name = "GitinspectorGUI"
# authors = [{ name = "GitinspectorGUI Team", email = "d.a.v.beek@tue.nl" }]
# dynamic = ["version", "description"]
